name: Run tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run
